environment:
  matrix:
    - nodejs_version: "8"
    - nodejs_version: "6"
    - nodejs_version: "4"

clone_depth: 1

branches:
  only:
  - master

version: "{build}"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node --version
  - npm --version
  - npm test

build: off

cache:
  - node_modules

matrix:
  fast_finish: true
